### PR TITLE
UI updated with Material Design style

### PR DESCRIPTION
**Pull request by ignacioinnovo**
This is a very useful program and I would like to contribute trying to improve the UX.

### CODE REVIEW

**Comment by ignacioinnovo** [comment]
Hi @XWolfOverride! I have deleted the fork as you recommended me.

Please, let me ask you a question: would you like to have a website? I can contribute with that :-) Perhaps something simple in Wordpress where we can upload the Releases versions ready to use!

Another question please, would you like me to speak in Spanish?

**Comment by XWolfOverride** [comment]
Hello @ignacioinnovo you deleted the fork? I think I press some button don't want, really it's ok for me if you have your own fork I don't know if accepting the change request will generate a delete fork message or something like that.

For the website I already have one [wolf.es](http://www.xwolf.es/) but this project does not have article (will do). It is my best proyect in terms of popularity on Github but sincerely this was a fast 1hr proyect done without any care, only fast and functional. Right now I'm taking some more care about code quality, memory impact and things like that.

For the language question, between english, spanish or portugese, you can talk in your preferred language. You give me the idea of add i18n to this project.

The next days I will add some changes to it remember to take a look to the final version.

**Comment by ignacioinnovo** [comment]
Nice @XWolfOverride! I think I can help you with all that things you mention. This is a good contribution for the great DuckDNS project.

May I contact you by e-mail? I couldn´t fin an e-mail address in your website. You can find my website and an e-mail address there if you prefer.

Congratulations for this project and let´s keep improving it!

**Comment by XWolfOverride** [comment]
My twitter is @XWolfOverride (I use the same nick for nearly all)

**Comment by ignacioinnovo** [comment]
Sorry but I don´t use Twitter.

If you want you can reach me by e-mail.

Have a nice day and congratulations again for this project!

**Pull request merged**
